image:
- Visual Studio 2017

branches:
  except:
    - l10n_master

init:
- ps: Install-Product node 10
- ps: |
    $env:PATH = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\;${env:PATH}"
    $env:DIST_DIR = "${env:APPVEYOR_BUILD_FOLDER}\dist\"
    $env:DIST_SRC_DIR = "${env:DIST_DIR}Source\"
    $env:REPO_URL = "https://github.com/${env:APPVEYOR_REPO_NAME}.git"
    $env:RELEASE_NAME = ""
    if($env:APPVEYOR_REPO_TAG -eq "true") {
      $env:RELEASE_NAME = "Version ${env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")}"
    }

install:
- cmd: npm install -g gulp
- ps: choco install cloc --no-progress
- ps: cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git

before_build:
- cmd: node --version
- cmd: npm --version

build_script:
- cmd: npm install
# Do normal build
- cmd: npm run dist
- cmd: npm run test
- cmd: gulp ci
# Build sources for reviewers
- cmd: |
    call git clone --branch=%APPVEYOR_REPO_BRANCH% %REPO_URL% %DIST_SRC_DIR%
    cd %DIST_SRC_DIR%
    call git checkout %APPVEYOR_REPO_COMMIT%
    call git submodule update --init --recursive
    cd %DIST_DIR%
    del /S/Q "%DIST_SRC_DIR%.git\objects\pack\*"
    call 7z a browser-source-%APPVEYOR_BUILD_NUMBER%.zip "%DIST_SRC_DIR%\*"
    cd %APPVEYOR_BUILD_FOLDER%

artifacts:
- path: dist/dist-opera-%APPVEYOR_BUILD_NUMBER%.zip
- path: dist/dist-chrome-%APPVEYOR_BUILD_NUMBER%.zip
- path: dist/dist-firefox-%APPVEYOR_BUILD_NUMBER%.zip
- path: dist/dist-edge-%APPVEYOR_BUILD_NUMBER%.appx
- path: dist/dist-safari-%APPVEYOR_BUILD_NUMBER%.zip
- path: dist/browser-source-%APPVEYOR_BUILD_NUMBER%.zip
- path: coverage/coverage-%APPVEYOR_BUILD_NUMBER%.zip

deploy:
  release: $(RELEASE_NAME)
  provider: GitHub
  auth_token: $(GH_TOKEN)
  artifact: /.*/
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
