files:
  - source: /src/_locales/en/messages.json
    translation: /src/_locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-PT: pt_PT
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW
